# #############################  Extracted using PyRadiomics version: <version>  ######################################

imageType:
  Original: {}
  LoG:
    # If you include sigma values >5, remember to also increase the padDistance. Because of resampling to (2, 2, 2), the
    # use of sigmas < 2 mm is not recommended.
    sigma: [2.0, 3.0, 4.0, 5.0]
  Wavelet: {}
  Square: {}
  SquareRoot: {}
  Logarithm: {}
  Exponential: {}


featureClass:
  shape:  
  firstorder:
  glcm:  
  glrlm:
  glszm:
  ngtdm:
  gldm:


setting:
  # Normalization:
  # MR signal is usually relative, with large differences between scanners and vendors. By normalizing the image before
  # feature calculation, this confounding effect may be reduced. However, if only one specific scanner is used, or the
  # images reflect some absolute world value (e.g. ADC maps, T2maps (NOT T2 weighted)), consider disabling the
  # normalization.
  normalize: True
  normalizeScale: 100  # This allows you to use more or less the same bin width.

  # Resampling:
  # If slices are very thin (~1mm), such as in 3D scanned (isotropic) volumes, resampledPixelSpacing may be reduced to
  # (1, 1, 1). Furthermore, in case of isotropic volumes, consider disabling resampling.
  # On a side note: increasing the resampled spacing forces PyRadiomics to look at more coarse textures, which may or
  # may not increase accuracy and stability of your extracted features.
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: [0.3, 0.3, 3.3]#median spacing of INT_Prostate t2w sequence

  # Image discretization:
  # The ideal number of bins is somewhere in the order of 16-128 bins. A possible way to define a good binwidt is to
  # extract firstorder:Range from the dataset to analyze, and choose a binwidth so, that range/binwidth remains approximately
  # in this range of bins.
  binWidth: 25  

  # first order specific settings:
  # When normalizing, gray values below the mean will be negative. Shifting by 300 (3 StdDevs * 100) ensures that the
  # majority of voxels is positive (only outliers >3 SD lower than the mean will be negative).
  voxelArrayShift: 300
  
  # 2D Extraction on axial planes for texture calculations:
  # Since we don't resample our image and the z dimension is considerably larger than x and y, it does not make sense
  # to compute 3D texture features
  #force2D: true
  #force2Ddimension: 0
  
  preCrop: true
  padDistance: 11
  
  

